### ISSUE TITLE
TAC RMS

### ISSUE THREAD

**Issue by 21esc12** [pennsnoplus/penn_daq#39]
Tac RMS values are roughly 30 on all ped_runs, when looking back in the original log files they where closer to 1?, could you look into this to make sure it is a none issue.

**Comment by bonventre** [comment]
This is an issue with using the soft gt instead of the pulser. Using the soft gt makes sure we send the right number of pedestals and so we can see accurately whether we are getting random hits, but it also makes the TAC jump by ~50 counts once every couple of hits which causes the tac rms to be larger. doing ped_run with a set frequency (-f) will fix this.
